In [1]:
import numpy as np

In [2]:
from sklearn.preprocessing import MinMaxScaler

In [3]:
data = np.random.randint(0,100,(10,2))

In [4]:
data

array([[57, 67],
       [79, 33],
       [55, 78],
       [84, 24],
       [42, 74],
       [92, 96],
       [ 9, 18],
       [20, 62],
       [65, 11],
       [76, 86]])

In [5]:
scaler_model = MinMaxScaler()

In [6]:
type(scaler_model)

sklearn.preprocessing.data.MinMaxScaler

In [7]:
scaler_model.fit(data)

/home/jhk/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:590: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [8]:
scaler_model.transform(data)

array([[0.57831325, 0.65882353],
       [0.84337349, 0.25882353],
       [0.55421687, 0.78823529],
       [0.90361446, 0.15294118],
       [0.39759036, 0.74117647],
       [1.        , 1.        ],
       [0.        , 0.08235294],
       [0.13253012, 0.6       ],
       [0.6746988 , 0.        ],
       [0.80722892, 0.88235294]])

In [9]:
scaler_model.fit_transform(data)

/home/jhk/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:590: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([[0.57831325, 0.65882353],
       [0.84337349, 0.25882353],
       [0.55421687, 0.78823529],
       [0.90361446, 0.15294118],
       [0.39759036, 0.74117647],
       [1.        , 1.        ],
       [0.        , 0.08235294],
       [0.13253012, 0.6       ],
       [0.6746988 , 0.        ],
       [0.80722892, 0.88235294]])

In [10]:
import pandas as pd

In [13]:
my_data = np.random.randint(0,101,(50,4))

In [17]:
df = pd.DataFrame(my_data, columns = ['f1', 'f2','f3', 'label'])

In [18]:
df

f1  f2   f3  label
0    45  98   99     27
1    31  15   72     17
2    14  35   30     55
3    53  33    0     82
4    85  36   89     86
5    62  51   40     71
6    57  46   79     10
7    43  61   60     64
8    95  13   44     91
9    10  78   10      6
10   54  66   38     71
11   84  30   36     36
12   76  57    9     26
13   88  57   80     27
14   83  44   51     68
15   78  80   97      8
16   68   6    3     76
17   50  46    9     80
18   57  55    0     13
19   69  31   90     41
20   83   5    6     94
21   59  50   26     51
22   72  50   73     52
23   67  72   74      8
24   79  84   68     33
25   35  34   14     16
26   70  48   14     62
27   31  70   89     36
28   36  33   49     52
29   68  10   45     84
30    6   9   28     96
31   40   4   84     61
32   60  66   96     57
33  100  79   20     79
34   76   0   86     11
35   82  45   81     16
36   44  77   29      4
37   72   2   37     53
38   50  66   11     21
39   10  51   22     89
40   44  51   76      4
41   36  64    4     48
42   55  94   33      7
43   64   2  100     19
44   12  40   75     77
45   65  31   54     52
46   50   6   95     97
47    1  31   68     74
48   16  59   55     28
49    7  21   24     54

In [19]:
X = df[['f1','f2','f3']]

In [25]:
y = df['label']

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [28]:
X_train.shape

(33, 3)

In [29]:
X_test.shape

(17, 3)